### ISSUE TITLE
Add "Swing Through Grass" mod

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/austere-caves#10]
### What is the problem you're trying to solve with this change?
Allows the player to swing through grass when fighting mobs
### What do you propose as a solution?
https://www.curseforge.com/minecraft/mc-mods/swingthroughgrass

**Comment by tungstonminer** [comment]
I opted not to include this mod during the intiial selection process.  I think it's more realistic that you would have problems hitting an enemy behind soft cover.
