### ISSUE TITLE
Server/client Optimizations

### ISSUE THREAD

**Issue by TheOne2160** [tungstonminer/austere-caves#16]
### What is the problem you're trying to solve with this change?
Optimizations

### What do you propose as a solution?

EntityCulling: makes entities not render if you cant see them, performance boost for clients. https://www.curseforge.com/minecraft/mc-mods/entityculling

DynamicView: Makes the server render distance go down if the server is lagging, brings it up again if it's smooth. ONLY NEEDED ON SERVER
https://www.curseforge.com/minecraft/mc-mods/dynamic-view

AI Improvements: Mod that improves the ai of mobs, so it might help with performance regarding lots of mobs in a mob farm, etc. ONLY NEEDED ON SERVER
https://www.curseforge.com/minecraft/mc-mods/ai-improvements

BetterFPS rendering: Renders in a circle and gives a fps boost. ONLY NEEDED ON CLIENT
https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance

FPS reducer: When you are AFK, the fps goes down. this improves computer performance if you switch to a different tab. ONLY NEEDED ON CLIENT
https://www.curseforge.com/minecraft/mc-mods/fps-reducer

**Comment by tungstonminer** [comment]
Looks like EntityCulling isn't available in the mod builder interface, but I've added all the others.
