### ISSUE TITLE
The blast furnace doesn't smelt copper as cheaply as it should

### ISSUE THREAD

**Issue by Royston52** [tungstonminer/austere-caves#17]
### What is the problem you're trying to solve with this change?

Blast Furnace only smelts 8 Raw Copper into 8 Copper ingots per 1 Coal. Should be 16.

### What do you propose as a solution?

Not the faintest idea.

**Comment by Royston52** [comment]
I,E.  16 raw copper should give16 copper ingots per single coal (or other fuel).

**Comment by tungstonminer** [comment]
I wasn't sure how blast furnaces work myself, so I looked them up on the [Minecraft wiki](https://minecraft.fandom.com/wiki/Blast_Furnace).  Turns out:

> Once an item and a fuel are placed into the blast furnace, the block state changes to lit and the item is smelted twice as fast as a regular furnace. Fuel is also used at double the rate of regular furnaces, so the number of items smelted per fuel stays the same.

So, I think this is probably working as intended.

**Comment by Royston52** [comment]
Im sure you are right.  I was going by a YT video, where it was categorically stated that the process works twice as fast and you could do sixteen at a time instead of eight.  It just shows you should not believe everything you watch.   I am beginning to wonder if they are worth it.  It would be better if you got twice the output, especially as the raw material is so scarce.  That would be more traditional.   I guess the same applies to the smoker.
